pr: none

jobs:
  - job: tests
    timeoutInMinutes: 120
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: docker info
      displayName: 'Info'

    - script: |
        docker-compose down
        docker-compose build --pull
        docker-compose pull
      displayName: 'Build Tests'

    - script: docker-compose run --rm tests81
      displayName: 'Run Tests PHP 8.1'
      env:
        ABS_ACCOUNT_NAME: $(ABS_ACCOUNT_NAME)
        ABS_ACCOUNT_KEY: $(ABS_ACCOUNT_KEY)
