version: "3"
services:
  # for development purposes
  tests: &tests
    build:
      context: .
      dockerfile: Dockerfile74
    environment:
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      # For Codeclimate
      - CC_TEST_REPORTER_ID
      - GIT_BRANCH
      - GIT_COMMIT_SHA
    command: ["composer", "ci"]

  tests-local:
    <<: *tests
    volumes:
      - ./:/code

  tests71:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile71

  tests72:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile72

  tests73:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile73

  tests74:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile74

  tests81:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile81
