version: "3"
services:
  # for development purposes
  tests: &tests
    build:
      context: .
      dockerfile: Dockerfile81
    environment:
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      # For Codeclimate
      - CC_TEST_REPORTER_ID
      - GIT_BRANCH
      - GIT_COMMIT_SHA
    command: ["composer", "ci"]

  tests-local:
    <<: *tests
    volumes:
      - ./:/code
  tests81:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile81
