services:
  # for development purposes
  tests: &tests
    build: .
    environment:
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      # For Codeclimate
      - CC_TEST_REPORTER_ID
      - GIT_BRANCH
      - GIT_COMMIT_SHA
    command: ["composer", "ci"]

  tests-local:
    <<: *tests
    volumes:
      - ./:/code

  tests81:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.1

  tests82:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.2

  tests83:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.3
